using System.Collections;
using System.Collections.Generic;
using UnityEngine; 

[CreateAssetMenu(menuName = "RPG Setup/Stat Setup", fileName = "Default Stat Setup")]
public class Stats_SetupSO : ScriptableObject
{
    public float damage;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
}
